### ISSUE TITLE
[ Refactor ] Layout 헤더 공간 추가

### ISSUE THREAD

**Issue by imddoy** [SOPT-all/35-COLLABORATION-WEB-MCDONALD#33]
### ♻️ Issue

페이지마다 헤더만큼 공간을 주는것이 비효율적이라 Layout에 공간 추가

### 🔢 리팩토링하는 이슈를 기입해주세요.

.

### 📝 To-do

- [ ] layout에 Spacing 컴포넌트 추가

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added Spacing component to Layout.tsx to provide consistent space for the header across all pages. This eliminates the need to add spacing on each individual page, making the code more efficient and maintainable.

You can review changes in this commit: https://github.com/lkilu6456546/SOPT-all-35-COLLABORATION-WEB-MCDONALD-33/commit/4cc2a21f41528abfd600d02dc4a45618ce414623.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
